[package]
name = "flowmesh-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
thiserror = "2.0.11"
bincode = "1.3.3"
serde = { version = "1.0.217", features = ["derive"] }
hex = "0.4"
